const caseTypes = [
  "single_turn",
  "scripted_multi_turn",
  "adaptive_multi_turn",
  "capability_probe",
  "boundary_risk",
  "regression_like",
];

const columns = [
  "caseId",
  "caseType",
  "capabilityCluster",
  "scenarioArchetype",
  "scenario",
  "userPersona",
  "userGoal",
  "modelFacingPrompt",
  "expectedOutcome",
  "mustDo",
  "mustNotDo",
  "failureModesToProbe",
  "riskLevel",
  "difficulty",
  "discriminativeSignal",
  "turn2UserMessage",
  "turn3UserMessage",
  "stopCondition",
  "notes",
];

export function buildManualTemplateWorkbook(activeTask) {
  const rows = caseTypes.map((caseType) => ({
    sheetName: caseType,
    rows: [
      columns,
      exampleRow(caseType, activeTask),
      emptyRow(caseType),
      emptyRow(caseType),
      emptyRow(caseType),
    ],
  }));
  rows.unshift({
    sheetName: "README",
    rows: [
      ["SBS Manual Eval Package Template"],
      ["Fill one row per eval case. Keep the file as XML Spreadsheet format when uploading."],
      ["Required columns: caseId, caseType, scenario, userPersona, userGoal, modelFacingPrompt, expectedOutcome, failureModesToProbe."],
      ["List fields can use semicolon-separated values."],
      ["For multi-turn cases, fill turn2UserMessage and turn3UserMessage when you want a fixed guided script."],
      ["Supported caseType values", caseTypes.join("; ")],
    ],
  });
  return xmlWorkbook(rows);
}

export function parseManualTemplateWorkbook(xmlText, activeTask) {
  const sheets = parseWorksheets(xmlText);
  const cases = [];
  for (const caseType of caseTypes) {
    const rows = sheets[caseType] || [];
    if (rows.length < 2) continue;
    const header = rows[0].map((item) => item.trim());
    for (const row of rows.slice(1)) {
      const record = Object.fromEntries(header.map((key, index) => [key, String(row[index] || "").trim()]));
      if (!record.caseId && !record.modelFacingPrompt && !record.scenario) continue;
      cases.push(recordToEvalCase({ ...record, caseType: record.caseType || caseType }, activeTask, cases.length + 1));
    }
  }
  if (!cases.length) throw new Error("No filled eval cases found in the uploaded template.");
  return buildRuntimePackageFromCases(cases, activeTask);
}

export function buildFallbackRuntimePackage(activeTask, caseCountTarget = 15, reason = "") {
  const count = [12, 15, 20].includes(Number(caseCountTarget)) ? Number(caseCountTarget) : 15;
  const plan = fallbackCaseTypePlan(count);
  const task = activeTask?.taskSpace || {};
  const arena = activeTask?.arena || {};
  const challenger = arena.challenger?.name || "Challenger";
  const baseline = arena.baseline?.name || "Doubao";
  const taskLabel = task.label || "目标任务空间";
  const audience = task.targetAudience || "目标用户";
  const capabilities = Array.isArray(task.mustCoverCapabilities) && task.mustCoverCapabilities.length
    ? task.mustCoverCapabilities
    : ["核心任务完成", "约束理解", "证据可靠性", "风险处理"];
  const risks = Array.isArray(task.riskAreas) && task.riskAreas.length ? task.riskAreas : ["来源可信性", "不确定性表达"];
  const records = plan.map((caseType, index) => {
    const capability = capabilities[index % capabilities.length];
    const risk = risks[index % risks.length];
    const n = String(index + 1).padStart(3, "0");
    return {
      caseId: `fallback-${caseType.replaceAll("_", "-")}-${n}`,
      caseType,
      capabilityCluster: capability,
      scenarioArchetype: fallbackArchetype(caseType),
      scenario: `${taskLabel}：面向${audience}，测试「${capability}」场景。`,
      userPersona: audience,
      userGoal: `在${taskLabel}中获得能帮助真实决策的建议。`,
      modelFacingPrompt: fallbackPrompt({ caseType, taskLabel, capability, risk, index }),
      expectedOutcome: `答案应围绕${capability}给出具体、可执行、符合用户背景的建议，并处理${risk}。`,
      mustDo: `理解用户任务; 覆盖${capability}; 给出可执行建议; 标注不确定性`,
      mustNotDo: `忽略核心约束; 编造实时或来源信息; 只给泛泛而谈的建议`,
      failureModesToProbe: `泛化回答; 约束遗漏; unsupported certainty; 任务漂移`,
      riskLevel: caseType === "boundary_risk" ? "high" : "medium",
      difficulty: ["scripted_multi_turn", "adaptive_multi_turn", "boundary_risk"].includes(caseType) ? "hard" : "medium",
      discriminativeSignal: `${challenger} 是否能在 ${taskLabel} 的 ${capability} 上提供比 ${baseline} 更有任务价值的结果。`,
      turn2UserMessage: caseType.includes("multi_turn") ? `我再补充一个约束：请把${risk}也考虑进去，并说明你为什么这样判断。` : "",
      turn3UserMessage: caseType.includes("multi_turn") ? "不用继续问太多了，请直接给我最终建议，并标注哪些地方需要我自己核验。" : "",
      stopCondition: caseType.includes("multi_turn") ? "输出最终可执行建议后停止。" : "",
      notes: reason ? `Fallback package because local Codex generation failed: ${reason}` : "Fallback package generated by SBS scaffold.",
    };
  });
  const pkg = buildRuntimePackageFromCases(records.map((record, index) => recordToEvalCase(record, activeTask, index + 1)), activeTask);
  pkg.generationTrace.generator = "sbs_fallback_scaffold_after_local_codex_failure";
  pkg.generationTrace.knownLimitations = [
    "This package was generated by a deterministic fallback scaffold because Local Codex did not return a package.",
    "It is structurally valid but weaker than the full chatbot-eval-set-generator skill output.",
  ];
  pkg.selfCritiqueTrace.findings.unshift({
    findingId: "fallback-generator-used",
    severity: "major",
    component: "overall",
    issue: "Local Codex generation failed, so SBS used a deterministic fallback scaffold.",
    whyItMatters: "The package can unblock UI review, but case originality and discriminative coverage may be weaker.",
    recommendedFix: "Retry Local Codex generation later or manually edit/replace cases before collection.",
    fixApplied: false,
    remainingRisk: reason || "Local Codex did not return a package.",
    confirmationBacklogRef: "fallback_generation_review",
    affectedCaseRefs: pkg.evalCases.map((item) => item.caseId),
    affectedDimensionRefs: pkg.evalSetCoveragePlan.enabledDimensions,
  });
  pkg.selfCritiqueTrace.overallReadiness = "needs_user_confirmation";
  pkg.selfCritiqueTrace.unresolvedConfirmationBacklogRefs = [
    ...new Set([...(pkg.selfCritiqueTrace.unresolvedConfirmationBacklogRefs || []), "fallback_generation_review"]),
  ];
  pkg.confirmationBacklog.unshift({
    id: "fallback_generation_review",
    component: "overall",
    relatedObjectIds: pkg.evalCases.map((item) => item.caseId),
    question: "Local Codex generation failed and SBS used a fallback scaffold. Do you want to keep, edit, or retry generation?",
    whyItMatters: "Fallback cases are structurally valid but may be less sharp than the skill-generated eval set.",
    recommendedDefault: "Review/edit cases, or retry Local Codex generation before serious collection.",
    severity: "important",
    blocksEvalRun: false,
    status: "pending_user",
  });
  return pkg;
}

function exampleRow(caseType, activeTask = {}) {
  const taskLabel = activeTask.taskSpace?.label || "餐厅推荐";
  return [
    `${caseType.replaceAll("_", "-")}-001`,
    caseType,
    "core_task",
    caseType === "boundary_risk" ? "unsupported_live_fact" : "realistic_user_need",
    `示例：${taskLabel}中的一个真实用户场景`,
    activeTask.taskSpace?.targetAudience || "目标用户画像",
    "用户想完成的任务目标",
    "用户会真实发给被测产品的一句话或第一轮消息",
    "理想结果应该满足的 outcome",
    "理解约束; 给出可执行建议; 标注不确定性",
    "编造实时事实; 忽略核心约束",
    "约束遗漏; 证据不足; 过度确定",
    caseType === "boundary_risk" ? "high" : "medium",
    "medium",
    "能区分强弱模型的关键信号",
    caseType.includes("multi_turn") ? "第二轮用户追问或补充约束" : "",
    caseType.includes("multi_turn") ? "第三轮收束问题或最终要求" : "",
    caseType.includes("multi_turn") ? "模型给出可执行最终结果后停止" : "",
    "可选备注",
  ];
}

function fallbackCaseTypePlan(count) {
  const base = [
    "single_turn",
    "single_turn",
    "single_turn",
    "single_turn",
    "single_turn",
    "scripted_multi_turn",
    "scripted_multi_turn",
    "scripted_multi_turn",
    "adaptive_multi_turn",
    "adaptive_multi_turn",
    "capability_probe",
    "capability_probe",
    "boundary_risk",
    "boundary_risk",
    "regression_like",
    "single_turn",
    "scripted_multi_turn",
    "capability_probe",
    "boundary_risk",
    "regression_like",
  ];
  return base.slice(0, count);
}

function fallbackArchetype(caseType) {
  return {
    single_turn: "one_shot_real_user_decision",
    scripted_multi_turn: "constraint_addition_and_convergence",
    adaptive_multi_turn: "clarification_and_drift_recovery",
    capability_probe: "single_capability_stress",
    boundary_risk: "unsupported_claim_or_risk_pushback",
    regression_like: "generic_baseline_regression",
  }[caseType] || "manual_scaffold";
}

function fallbackPrompt({ caseType, taskLabel, capability, risk, index }) {
  if (caseType === "boundary_risk") {
    return `我在做${taskLabel}决策，想要一个很确定的推荐。请直接告诉我最值得选的方案，并说明你能确认哪些信息；如果涉及${risk}，也请明确哪些需要我自己核验。`;
  }
  if (caseType === "capability_probe") {
    return `帮我围绕${taskLabel}做一个推荐，重点考察${capability}。请不要泛泛而谈，给出具体判断标准和取舍。`;
  }
  if (caseType.includes("multi_turn")) {
    return `我想做一个${taskLabel}相关决策，但还没想清楚。你先帮我判断应该怎么选。`;
  }
  if (caseType === "regression_like") {
    return `请给我一个${taskLabel}的推荐清单，要求不是普通榜单，要解释为什么适合我。`;
  }
  return `我现在需要做${taskLabel}相关决策，重点在${capability}。请给我几个具体选择、推荐理由、风险提醒和需要核验的信息。`;
}

function emptyRow(caseType) {
  return ["", caseType, "", "", "", "", "", "", "", "", "", "", "medium", "medium", "", "", "", "", ""];
}

function recordToEvalCase(record, activeTask = {}, index) {
  const caseId = record.caseId || `manual-${String(index).padStart(3, "0")}`;
  const modelFacingPrompt = record.modelFacingPrompt || record.initialPrompt || record.scenario;
  const mustDo = splitList(record.mustDo);
  const mustNotDo = splitList(record.mustNotDo);
  const failureModes = splitList(record.failureModesToProbe);
  return {
    caseId,
    caseType: sanitizeCaseType(record.caseType),
    capabilityCluster: record.capabilityCluster || "manual_import",
    scenarioArchetype: record.scenarioArchetype || "manual_import",
    scenario: record.scenario || modelFacingPrompt,
    userPersona: record.userPersona || activeTask.taskSpace?.targetAudience || "Target user",
    userGoal: record.userGoal || record.expectedOutcome || "Complete the task successfully.",
    userFacingIntent: record.userGoal || record.scenario || modelFacingPrompt,
    evaluatorIntent: record.expectedOutcome || "Evaluate whether the answer satisfies the task outcome.",
    hiddenIntent: record.notes || "Manual-imported case; use evaluator fields only for grading context.",
    constraints: [...mustDo, ...mustNotDo.map((item) => `Avoid: ${item}`)],
    initialPrompt: modelFacingPrompt,
    modelFacingPrompt,
    collectionInstructions: ["Send the model-facing prompt manually to both products.", "Capture final output and visible evidence."],
    doNotRevealToModel: ["evaluatorIntent", "hiddenIntent", "expectedOutcome", "failureModesToProbe"],
    exposureContract: {
      modelVisibleFactsAtStart: [modelFacingPrompt],
      evaluatorOnlyFacts: [record.userPersona, record.expectedOutcome, record.notes].filter(Boolean),
      hardScoringRequirements: mustDo.map((requirement) => ({
        requirement,
        source: "model_facing_prompt",
        eligibleFromTurn: 1,
        relatedFields: ["modelFacingPrompt", "mustDo"],
      })),
      inferenceTargets: [record.discriminativeSignal || "task success"].filter(Boolean),
      nonScoringContext: [record.notes].filter(Boolean),
      fairnessNotes: "Hard scoring should use only model-visible facts or reasonable inference.",
    },
    expectedOutcome: record.expectedOutcome || "A useful, accurate, constraint-aware answer.",
    acceptableOutcomes: ["Satisfies the user goal with clear tradeoffs and appropriate uncertainty."],
    unacceptableOutcomes: ["Ignores the user goal, invents unsupported facts, or gives unsafe/confidently wrong claims."],
    mustDo: mustDo.length ? mustDo : ["Address the user goal", "Respect visible constraints"],
    mustNotDo: mustNotDo.length ? mustNotDo : ["Invent unsupported facts"],
    failureModesToProbe: failureModes.length ? failureModes : ["generic answer", "constraint omission", "unsupported certainty"],
    riskLevel: ["low", "medium", "high"].includes(record.riskLevel) ? record.riskLevel : "medium",
    difficulty: ["easy", "medium", "hard"].includes(record.difficulty) ? record.difficulty : "medium",
    discriminativeSignal: record.discriminativeSignal || "Whether the model produces a genuinely useful task outcome.",
    evidenceRequired: { minimumLevel: "L0", notes: "Manual-imported cases can run with final output only." },
    collectionMode: record.caseType?.includes("multi_turn") ? "manual_multi_turn" : "manual_single_prompt",
    estimatedUserEffort: record.caseType?.includes("multi_turn") ? "medium" : "low",
    graderRefs: ["manual_import_default_rubric"],
    confirmationBacklogRefs: [],
    importNotes: record.notes || "",
    manualTemplateTurns: [record.turn2UserMessage, record.turn3UserMessage].filter(Boolean),
    manualStopCondition: record.stopCondition || "",
  };
}

function buildRuntimePackageFromCases(evalCases, activeTask = {}) {
  const now = new Date().toISOString();
  const task = activeTask.taskSpace || {};
  const arena = activeTask.arena || {};
  const multiTurnCases = evalCases.filter((item) => item.caseType.includes("multi_turn"));
  return {
    arenaEvalSpec: {
      taskSpace: task.label || "Manual task space",
      evaluationScenario: task.concreteScenario || task.label || "Manual evaluation scenario",
      decisionContext: task.winningCriteria || "",
      decisionQuestion: task.decisionQuestion || `${arena.challenger?.name || "Challenger"} 是否胜出 ${arena.baseline?.name || "Doubao"}？`,
      targetUsers: splitList(task.targetAudience || "Target users"),
      userJobs: splitList(task.winningCriteria || task.concreteScenario || task.label || "Complete the task"),
      baseline: arena.baseline || { name: "Doubao" },
      challenger: arena.challenger || { name: "Challenger" },
      productSurface: `${arena.baseline?.surface || "web_chat"} vs ${arena.challenger?.surface || "web_chat"}`,
      baselineUseMode: arena.baseline?.surface || "web_chat",
      challengerUseMode: arena.challenger?.surface || "web_chat",
      assumptions: ["Manual-imported eval package."],
      knownUnknowns: ["Manual import may not include full coverage rationale."],
      confidence: "medium",
      successDefinition: task.winningCriteria || "The winning product better satisfies task outcomes across cases.",
      failureDefinition: "A product fails when it ignores constraints, produces unsupported claims, or cannot complete the user job.",
      riskBoundaries: task.riskAreas || [],
      evidenceAssumptions: ["Final output is always collected; visible evidence is optional."],
      requiresUserConfirmation: true,
      clarificationQuestions: [
        {
          id: "manual_import_review",
          question: "Are the manually imported cases realistic, diverse, and aligned with the task-space decision?",
          whyItMatters: "The parser validates structure, but the user must confirm eval quality.",
          recommendedDefault: "Review every imported case in Cases before collection.",
          blocksGeneration: false,
        },
      ],
    },
    evalSetCoveragePlan: {
      defaultDimensions: ["intentUnderstanding", "outcomeQuality", "evidenceGrounding", "riskHandling", "trajectoryControl"],
      scoredDimensions: ["intentUnderstanding", "outcomeQuality", "evidenceGrounding", "riskHandling"],
      diagnosticDimensions: multiTurnCases.length ? ["trajectoryControl"] : [],
      baselineInsightDimensions: [],
      enabledDimensions: [
        "intentUnderstanding",
        "outcomeQuality",
        "evidenceGrounding",
        "riskHandling",
        ...(multiTurnCases.length ? ["trajectoryControl"] : []),
      ],
      disabledDimensions: activeTask.taskSpace?.evaluateConversationExperience ? [] : ["productExperience"],
      dimensionWeights: { intentUnderstanding: 0.25, outcomeQuality: 0.35, evidenceGrounding: 0.25, riskHandling: 0.15 },
      scalePreset: "mvp",
      caseMix: countBy(evalCases, "caseType"),
      caseCountTarget: evalCases.length,
      caseTypeRationale: { manual_import: "User supplied case rows through the SBS manual template." },
      difficultyMix: countBy(evalCases, "difficulty"),
      riskMix: countBy(evalCases, "riskLevel"),
      singleTurnRatio: (evalCases.length - multiTurnCases.length) / evalCases.length,
      multiTurnRatio: multiTurnCases.length / evalCases.length,
      optionalExperiencePersonaModule: { enabled: Boolean(activeTask.taskSpace?.evaluateConversationExperience) },
      taskFitModule: {
        status: activeTask.taskSpace?.nativeContextPolicy ? "scored" : "diagnostic_only",
        relationshipToProductExperience: "task_value_not_product_experience",
        fitSignals: splitList(activeTask.arena?.challenger?.expectedAdvantage || ""),
        sourceContextSignals: splitList(activeTask.taskSpace?.nativeContextPolicy || ""),
        scoredThroughDimensions: ["outcomeQuality", "intentUnderstanding"],
        rewardPolicy: activeTask.taskSpace?.nativeContextPolicy || "Reward task-relevant fit only when it improves outcome quality.",
        penaltyPolicy: "Do not excuse unsupported live or source-certainty claims.",
        rationale: "Manual-imported task-fit policy derived from task setup.",
        confirmationBacklogRefs: [],
      },
      coverageGaps: ["Manual template import does not run the full self-critique generation loop."],
      confirmationBacklogRefs: ["manual_import_review"],
      coverageRationale: "Coverage is based on user-provided rows.",
      requiresUserConfirmation: true,
    },
    evalCases,
    turnScripts: multiTurnCases.map(caseToTurnScript),
    rubricSuggestions: buildRubricSuggestions(evalCases),
    reportSkeletonMetadata: {
      reportId: `manual-import-${now.replaceAll(":", "").replaceAll(".", "")}`,
      title: `${task.label || "Manual Eval"} SBS Report`,
      reportAudience: "Agent PM",
      decisionMode: "side_by_side_task_space_decision",
      scoreboardDimensions: ["intentUnderstanding", "outcomeQuality", "evidenceGrounding", "riskHandling"],
      caseClusters: Object.keys(countBy(evalCases, "capabilityCluster")),
      riskSections: ["riskHandling", "unsupportedClaims", "collectionCaveats"],
      baselineInsightSections: ["baselineStrengths", "baselineWeaknesses"],
      recommendedAppendices: ["case-index.md", "rawCollectedOutputs", "manualImportTemplate"],
      rawArtifactLinks: ["case-index.md", "uploaded-template.xml"],
      humanOverrideFields: ["reviewerNotes", "readyForGrading", "manualWinner", "manualRationale"],
      audience: "Agent PM",
      requiredSections: ["Arena", "Coverage", "Per-case SBS", "Dimension Summary", "Caveats", "Optimization Suggestions"],
      createdAt: now,
    },
    generationTrace: {
      generationRunId: `manual-import-${now.replaceAll(":", "").replaceAll(".", "")}`,
      generator: "manual_template_import",
      packageVersion: "v1",
      artifactRefs: ["case-index.md"],
    },
    selfCritiqueTrace: {
      mode: "manual_import_lightweight_check",
      findings: [
        {
          findingId: "manual-import-quality-review",
          severity: "minor",
          component: "overall",
          issue: "Manual template import does not run the full generator self-critique loop.",
          whyItMatters: "The imported package can be structurally valid while still containing weak or overlapping cases.",
          recommendedFix: "Review all imported cases in Cases view before approving for collection.",
          fixApplied: false,
          remainingRisk: "Coverage and discriminative signal depend on the user-filled rows.",
          confirmationBacklogRef: "manual_import_review",
          affectedCaseRefs: evalCases.map((item) => item.caseId),
          affectedDimensionRefs: ["intentUnderstanding", "outcomeQuality", "evidenceGrounding", "riskHandling"],
        },
      ],
      qualityGateResults: {
        arenaCompleteness: { status: "warn", reason: "Arena is derived from task setup and manual rows; user review recommended." },
        coverageRepresentativeness: { status: "warn", reason: "Coverage depends on uploaded rows." },
        caseQuality: { status: "warn", reason: "Cases are structurally valid but not model-generated/self-critiqued." },
      },
      revisionPasses: [
        {
          passIndex: 1,
          changesApplied: ["Filled required runtime package fields from manual template rows."],
          reason: "Convert user-authored rows into executable SBS package structure.",
        },
      ],
      revisionSummary: "No model self-critique was run for manual import.",
      unresolvedConfirmationBacklogRefs: ["manual_import_review"],
      traceArtifactRefs: ["case-index.md"],
      overallReadiness: "ready_with_caveats",
    },
    confirmationBacklog: [
      {
        id: "manual_import_review",
        component: "overall",
        relatedObjectIds: evalCases.map((item) => item.caseId),
        question: "Please review imported cases before collection.",
        whyItMatters: "The manual template parser can validate structure, but cannot guarantee discriminative eval quality.",
        recommendedDefault: "Review in Cases page, edit weak cases, approve only usable cases.",
        severity: "important",
        blocksEvalRun: false,
        status: "pending_user",
      },
    ],
  };
}

function caseToTurnScript(evalCase) {
  const extraTurns = evalCase.manualTemplateTurns || [];
  const turns = [evalCase.modelFacingPrompt, ...extraTurns].map((message, index) => ({
    turnIndex: index + 1,
    progressLabel: `Turn ${index + 1}`,
    modelFacingUserMessage: message,
    evaluatorInstruction: index === 0 ? "Start the manual multi-turn case." : "Continue the case with the supplied user message.",
    intentionToPush: evalCase.evaluatorIntent,
    expectedStateAfterTurn: evalCase.expectedOutcome,
    exposureDelta: {
      exposedFactsBeforeTurn: index === 0 ? [] : [evalCase.modelFacingPrompt],
      newlyExposedFacts: [message],
      modelVisibleRequirementsAfterTurn: [message],
      allowedNewFactsToExpose: [message],
    },
    allowedAdaptiveMoves: ["Ask one fair follow-up that preserves the user's visible intent."],
    branchRules: [
      {
        branchRuleId: `${evalCase.caseId}-manual-${index + 1}`,
        condition: "Default manual guided continuation.",
        action: "send_manual_template_turn",
        modelFacingReply: message,
        evaluatorNote: "Manual-imported turn.",
        continueToTurn: index + 2,
      },
    ],
    ifModelDrifts: "Restate visible constraints and ask for a revised answer.",
    ifModelAsksClarifyingQuestion: "Answer using only visible case constraints.",
    ifModelOverpromises: "Ask how it knows and request uncertainty marking.",
    ifModelRefusesOrCannotAnswer: "Ask for a best-effort response with uncertainty clearly marked.",
  }));
  return {
    caseId: evalCase.caseId,
    scriptMode: "guided_adaptive",
    maxTurns: turns.length,
    stateToTrack: ["visible constraints", "drift", "uncertainty"],
    fairnessPolicy: "Use the same shared user message for both sides.",
    doNotRevealToModel: evalCase.doNotRevealToModel,
    runtimeStateTemplate: {
      cursorFields: ["evalRunId", "caseId", "currentTurnIndex", "sideLabel"],
      packageBindingFields: ["evalPackageId", "evalPackageVersion"],
      upstreamContextFields: ["arenaEvalSpec.summary", "evalCases[caseId].summary"],
      transcriptFields: ["priorTurns", "lastModelResponse"],
      decisionFields: ["branchRules", "stateToTrack", "stopCondition"],
      safetyFields: ["doNotRevealToModel", "exposureContract"],
      outputFields: [
        "selectedAction",
        "selectedBranchRuleId",
        "modelFacingUserMessage",
        "evaluatorNote",
        "newlyExposedFacts",
        "updatedTrackedState",
        "shouldStop",
        "stopReason",
        "trajectoryNotes",
      ],
    },
    harnessExecutionContract: {
      runtimeModelMode: "manual_driver",
      cursorOwner: "harness",
      sideBlind: true,
      decisionPolicy: "branch_rules_only",
      branchFallbackPolicy: "allowed_adaptive_moves_or_needs_human_review",
      preSendValidation: [
        "package_binding",
        "branch_rule_exists",
        "no_evaluator_leakage",
        "no_unapproved_exposure",
        "no_unapproved_constraints",
        "tracked_state_whitelist",
        "max_turns_stop_condition",
      ],
      replayLogFields: ["state_packet", "simulator_output", "validator_result", "final_user_message"],
      plannerDrafterSplit: "not_applicable",
      humanReviewFallbackRequired: true,
    },
    turns,
    stopCondition: evalCase.manualStopCondition || "Stop when the user task has a final answer or maxTurns is reached.",
    collectionBurden: turns.length > 2 ? "medium" : "low",
  };
}

function buildRubricSuggestions(evalCases) {
  return [
    rubric("intentUnderstanding", 0.25, evalCases, ["single_turn", "scripted_multi_turn", "adaptive_multi_turn", "capability_probe", "boundary_risk", "regression_like"]),
    rubric("outcomeQuality", 0.35, evalCases, ["single_turn", "scripted_multi_turn", "adaptive_multi_turn", "capability_probe", "regression_like"]),
    rubric("evidenceGrounding", 0.25, evalCases, ["single_turn", "scripted_multi_turn", "adaptive_multi_turn", "capability_probe", "boundary_risk", "regression_like"]),
    rubric("riskHandling", 0.15, evalCases, ["boundary_risk", "single_turn", "scripted_multi_turn", "adaptive_multi_turn"]),
  ];
}

function rubric(dimensionId, weightSuggestion, evalCases, appliesToCaseTypes) {
  return {
    dimensionId,
    dimensionState: "scored",
    appliesToCaseTypes,
    appliesToCaseTags: [],
    caseRefs: evalCases.filter((item) => appliesToCaseTypes.includes(item.caseType)).map((item) => item.caseId),
    weightSuggestion,
    scoreScale: "1-5",
    scoreAnchors: { high: "Clearly satisfies the dimension.", medium: "Partially satisfies with caveats.", low: "Misses or harms the dimension." },
    scoringMethod: ["pairwise_side_by_side", "evidence_based"],
    positiveSignals: ["Uses visible user intent", "Produces actionable output", "Marks uncertainty when needed"],
    negativeSignals: ["Ignores constraints", "Invents unsupported facts", "Overconfident live claims"],
    redLineFailures: [
      {
        failureId: `${dimensionId}_unsafe_or_fabricated`,
        description: "Severe unsupported or unsafe claim in this dimension.",
        scoreCap: 2,
        appliesWhen: "Evidence shows a high-impact unsupported claim.",
        evidenceRequired: "Collected output or visible evidence.",
        suggestedAction: "Cap score and mark for human review.",
      },
    ],
    evidenceSources: ["final_output", "visible_process", "source_notes", "followup_suggestions"],
    evidenceRequired: "Use only collected, model-visible, or reasonably inferable evidence.",
    judgeTypeSuggestion: "llm_with_human_review",
    judgePlan: {
      primaryJudge: "LLM grader after collection",
      fallbackJudge: "Human PM review",
      humanSamplingRecommendation: "Review all low-confidence or red-line cases.",
      calibrationNotes: "Manual import rubrics are generic and should be refined before formal scoring.",
      blindPairwiseRecommended: true,
    },
    uncertaintyPolicy: "Mark low confidence when evidence fields are missing or provider capabilities differ.",
    aggregationHint: "Aggregate by dimension and case type.",
    humanOverridePolicy: "Human reviewer can override with written rationale.",
    confirmationBacklogRefs: ["manual_import_review"],
  };
}

function xmlWorkbook(sheets) {
  return `<?xml version="1.0"?>\n<?mso-application progid="Excel.Sheet"?>\n<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet">\n${sheets
    .map(sheetXml)
    .join("\n")}\n</Workbook>\n`;
}

function sheetXml(sheet) {
  return `  <Worksheet ss:Name="${escapeXml(sheet.sheetName)}">\n    <Table>\n${sheet.rows
    .map(rowXml)
    .join("\n")}\n    </Table>\n  </Worksheet>`;
}

function rowXml(row) {
  return `      <Row>${row.map((cell) => `<Cell><Data ss:Type="String">${escapeXml(cell)}</Data></Cell>`).join("")}</Row>`;
}

function parseWorksheets(xmlText) {
  const out = {};
  const worksheetRegex = /<Worksheet\b[^>]*(?:ss:)?Name="([^"]+)"[^>]*>([\s\S]*?)<\/Worksheet>/g;
  let match;
  while ((match = worksheetRegex.exec(xmlText))) {
    const name = unescapeXml(match[1]);
    const body = match[2];
    const rows = [];
    const rowRegex = /<Row\b[^>]*>([\s\S]*?)<\/Row>/g;
    let rowMatch;
    while ((rowMatch = rowRegex.exec(body))) {
      const cells = [];
      const cellRegex = /<Cell\b[^>]*>([\s\S]*?)<\/Cell>/g;
      let cellMatch;
      while ((cellMatch = cellRegex.exec(rowMatch[1]))) {
        const dataMatch = cellMatch[1].match(/<Data\b[^>]*>([\s\S]*?)<\/Data>/);
        cells.push(unescapeXml(dataMatch ? dataMatch[1] : ""));
      }
      rows.push(cells);
    }
    out[name] = rows;
  }
  return out;
}

function sanitizeCaseType(value) {
  return caseTypes.includes(value) ? value : "single_turn";
}

function splitList(value) {
  if (Array.isArray(value)) return value.map((item) => String(item).trim()).filter(Boolean);
  return String(value || "")
    .split(/\n|;|；/)
    .map((item) => item.trim())
    .filter(Boolean);
}

function countBy(items, key) {
  return items.reduce((acc, item) => {
    const value = item[key] || "unknown";
    acc[value] = (acc[value] || 0) + 1;
    return acc;
  }, {});
}

function escapeXml(value) {
  return String(value ?? "")
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");
}

function unescapeXml(value) {
  return String(value ?? "")
    .replaceAll("&quot;", '"')
    .replaceAll("&gt;", ">")
    .replaceAll("&lt;", "<")
    .replaceAll("&amp;", "&");
}
